### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'scale'

### ISSUE THREAD

**Issue by markkurt** [DSaurus/threestudio-dreamcraft3D#1]
When running:
```
python launch.py --config custom/threestudio-dreamcraft3D/configs/dreamcraft3d-texture.yaml --train system.prompt_processor.prompt="$prompt" data.image_path="$image_path" system.geometry_convert_from="$ckpt"
```

**Comment by DSaurus** [comment]
Hi, @markkurt 

Could you please provide more detailed information about this error?

**Comment by markkurt** [comment]
sure - sorry, here's the call stack:

```
Epoch 0: |                                                                               | 0/? [00:00<?, ?it/s]Traceback (most recent call last):
  File "launch.py", line 301, in <module>
    main(args, extras)
  File "launch.py", line 244, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1282, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 264, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/optim/adamw.py", line 161, in step
    loss = closure()
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision.py", line 104, in _wrap_closure
    closure_result = closure()
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 381, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 633, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 626, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/home/markcolkurt/threestudio/custom/threestudio-dreamcraft3D/system/dreamcraft3d.py", line 420, in training_step
    out = self.training_substep(
  File "/home/markcolkurt/threestudio/custom/threestudio-dreamcraft3D/system/dreamcraft3d.py", line 222, in training_substep
    guidance_out = self.guidance(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/custom/threestudio-dreamcraft3D/guidance/stable_diffusion_bsd_guidance.py", line 1159, in forward
    loss_pretrain = self.train_pretrain(
  File "/home/markcolkurt/threestudio/custom/threestudio-dreamcraft3D/guidance/stable_diffusion_bsd_guidance.py", line 1015, in train_pretrain
    images_sample = self._sample(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/markcolkurt/threestudio/custom/threestudio-dreamcraft3D/guidance/stable_diffusion_bsd_guidance.py", line 402, in _sample
    noise_pred = unet(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 915, in forward
    sample, res_samples = downsample_block(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 996, in forward
    hidden_states = attn(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/diffusers/models/transformer_2d.py", line 292, in forward
    hidden_states = block(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 155, in forward
    attn_output = self.attn1(
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/markcolkurt/threestudio/venv/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 322, in forward
    return self.processor(
TypeError: __call__() got an unexpected keyword argument 'scale'
```

Python 3.8.10
CUDA 11.8

Name: xformers
Version: 0.0.23.post1+cu118

Name: torch
Version: 2.1.2+cu118

Name: torchvision
Version: 0.16.2+cu118

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

I've pulled the latest on threestudio and threestudio-dreamcraft3D as of this morning.

Let me know if more information would be helpful.  I did go through an remove references to scale in `stable_diffusion_bsd_guidance.py` and it does get me past the problem (but unsure about what other problems that will cause - the training hangs at around iteration 1200, but the intermediate results look good)

**Comment by DSaurus** [comment]
I think the problem is caused by diffusers. What is your diffuser version? I'm using diffusers==0.24.0.

**Comment by markkurt** [comment]
My current version was 0.19.3

I updated to 0.24.0 and it's working.  Thank you!
