### ISSUE TITLE
Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the quantized model.

### ISSUE THREAD

**Issue by liuyulinn** [DSaurus/threestudio-dreamcraft3D#12]
Hi,

I got the ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu for more details.

I'm using RTX4090 with 24 GB GPU memory. As indicated by your documents, it will take about 3 hours and ~22G GPU memory to run all stages, I guess I have enough memory. So what's wrong with it and how can I fix it?

Thanks!

**Comment by sidsunny** [comment]
Hi, I get the same ValueError, and at the end of the error log, the following - AssertionError: prompt embedding process failed!

This is the complete error log:
``` bin /home/sseth/anaconda3/envs/threestudio6/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/sseth/anaconda3/envs/threestudio6/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/sseth/anaconda3/envs/threestudio6/lib/libcudart.so.11.0'), PosixPath('/home/sseth/anaconda3/envs/threestudio6/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/sseth/anaconda3/envs/threestudio6/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/sseth/anaconda3/envs/threestudio6/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/sseth/anaconda3/envs/threestudio6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sseth/anaconda3/envs/threestudio6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nvme0/sseth/codes/threestudio/threestudio/models/prompt_processors/deepfloyd_prompt_processor.py", line 61, in spawn_func
    text_encoder = T5EncoderModel.from_pretrained(
  File "/home/sseth/anaconda3/envs/threestudio6/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2740, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.                     
Traceback (most recent call last):
  File "/nvme0/sseth/codes/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/nvme0/sseth/codes/threestudio/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/nvme0/sseth/codes/threestudio/threestudio/systems/base.py", line 51, in __init__
    self.configure()
  File "/nvme0/sseth/codes/threestudio/custom/threestudio-dreamcraft3D/system/dreamcraft3d.py", line 47, in configure
    self.prompt_processor = threestudio.find(self.cfg.prompt_processor_type)(
  File "/nvme0/sseth/codes/threestudio/threestudio/utils/base.py", line 83, in __init__
    self.configure(*args, **kwargs)
  File "/nvme0/sseth/codes/threestudio/threestudio/models/prompt_processors/base.py", line 344, in configure
    self.prepare_text_embeddings()
  File "/home/sseth/anaconda3/envs/threestudio6/lib/python3.9/site-packages/lightning_utilities/core/rank_zero.py", line 43, in wrapped_fn
    return fn(*args, **kwargs)
  File "/nvme0/sseth/codes/threestudio/threestudio/models/prompt_processors/base.py", line 390, in prepare_text_embeddings
    assert subprocess.exitcode == 0, "prompt embedding process failed!"
AssertionError: prompt embedding process failed!

I have tried this on both 24G A5000 and RTX 3090.

**Comment by liuyulinn** [comment]
Hi, I've tried A100, and it can work now.

**Comment by sidsunny** [comment]
I found that getting text embeddings requires 2x24G GPUs and the rest of the stages can run on a single 24G card.
