### ISSUE TITLE
KeyError: 'stable-zero123-guidance' in frist python cmd

### ISSUE THREAD

**Issue by r530044129** [DSaurus/threestudio-dreamcraft3D#3]
In first step, I input this: python launch.py --config custom/threestudio-dreamcraft3D/configs/dreamcraft3d-coarse-nerf.yaml --train system.prompt_processor.prompt="a delicious hamburger" data.image_path="load/images/hamburger_rgba.png"

But I met those error, here is the log:

Import times for custom modules:
   0.0 seconds: custom/threestudio-stable-nerf-renderer
   0.1 seconds: custom/threestudio-mvdream
   0.1 seconds: custom/threestudio-4dfy
   0.4 seconds: custom/threestudio-dreamcraft3D

Seed set to 0
[INFO] Loading Deep Floyd ...

A mixture of fp16 and non-fp16 filenames will be loaded.
Loaded fp16 filenames:
[text_encoder/model.fp16-00001-of-00002.safetensors, text_encoder/model.fp16-00002-of-00002.safetensors, safety_checker/model.fp16.safetensors, unet/diffusion_pytorch_model.fp16.safetensors]
Loaded non-fp16 filenames:
[watermarker/diffusion_pytorch_model.safetensors
If this behavior is not expected, please check your folder structure.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████| 3/3 [00:00<00:00,  5.86it/s]
[INFO] Loaded Deep Floyd!
Traceback (most recent call last):
  File "/home/dreamer/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 45, in __init__
    self.configure()
  File "/home/dreamer/threestudio/custom/threestudio-dreamcraft3D/system/dreamcraft3d.py", line 42, in configure
    self.guidance_3d = threestudio.find(self.cfg.guidance_3d_type)(
  File "/home/dreamer/threestudio/threestudio/__init__.py", line 13, in find
    return __modules__[name]
KeyError: 'stable-zero123-guidance'

**Comment by r530044129** [comment]
I've login huggingface and download zero123 (about 14GB)

**Comment by DSaurus** [comment]
Hi @r530044129 ,

You can try to update your threestudio by pull from the github.

**Comment by r530044129** [comment]
i update, but there is another error:
```
Traceback (most recent call last):
  File "/home/dreamer/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 51, in __init__
    self.configure()
  File "/home/dreamer/threestudio/custom/threestudio-dreamcraft3D/system/dreamcraft3d.py", line 42, in configure
    self.guidance_3d = threestudio.find(self.cfg.guidance_3d_type)(
  File "/home/dreamer/threestudio/threestudio/utils/base.py", line 83, in __init__
    self.configure(*args, **kwargs)
  File "/home/dreamer/threestudio/threestudio/models/guidance/stable_zero123_guidance.py", line 105, in configure
    self.model = load_model_from_config(
  File "/home/dreamer/threestudio/threestudio/models/guidance/stable_zero123_guidance.py", line 41, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/dreamer/.local/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dreamer/.local/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dreamer/.local/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './load/zero123/stable_zero123.ckpt'
```

I found that the .ckpt is named "105000.ckpt" instead of "stable_zero123.ckpt", so I manually change its name to stable_zero123.ckpt, and run again, It's work!

**Comment by DSaurus** [comment]
Good job! I suggest that you redownload the checkpoint with the updated download script because `105000.ckpt` is zero123-xl instead of stable-zero123.

**Comment by r530044129** [comment]
Get it, so is there any difference between ‘zero123-xl’ and 'stable-zero123'?

**Comment by altava-sgp** [comment]
> Get it, so is there any difference between ‘zero123-xl’ and 'stable-zero123'?

https://stability.ai/news/stable-zero123-3d-generation

**Comment by r530044129** [comment]
> > Get it, so is there any difference between ‘zero123-xl’ and 'stable-zero123'?
> 
> https://stability.ai/news/stable-zero123-3d-generation

OK，stable-zero123 is better, I should download this one
