### ISSUE TITLE
Export mesh failed after Stage 2 (Geometry Refinement)

### ISSUE THREAD

**Issue by r530044129** [DSaurus/threestudio-dreamcraft3D#5]
Here is my code:
```
python launch.py --config outputs/dreamcraft3d-geometry/a_warrior,_hero@20231221-050728/configs/parsed.yaml  --export --gpu 0 resume=outputs/dreamcraft3d-geometry/a_warrior,_hero@20231221-050728/ckpts/last.ckpt system.exporter_type=mesh-exporter system.exporter.context_type=cuda
```

Part of the failed log:

```
loaded pretrained LPIPS loss from threestudio/utils/lpips/vgg.pth
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[INFO] ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] single image dataset: load image zrj_input/ai/hero_rgba.png torch.Size([1, 1024, 1024, 3])
[INFO] Restoring states from the checkpoint path at outputs/dreamcraft3d-geometry/a_warrior,_hero@20231221-050728/ckpts/last.ckpt
Traceback (most recent call last):
  File "/home/dreamer/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/launch.py", line 259, in main
    trainer.predict(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in predict
    return call._call_and_handle_interrupt(
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 903, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 955, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 273, in restore_model
    call._call_lightning_module_hook(trainer, "on_load_checkpoint", self._loaded_checkpoint)
  File "/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/dreamer/threestudio/custom/threestudio-dreamcraft3D/system/dreamcraft3d.py", line 629, in on_load_checkpoint
    "guidance." + k: v for (k, v) in self.guidance.state_dict().items()
AttributeError: 'DeepFloydGuidance' object has no attribute 'state_dict'
```

**Comment by DSaurus** [comment]
Hi @r530044129 ,

This is a bug, I have fixed it and added some instructions for mesh export in README.md.
