### ISSUE TITLE
I got error while exporting mesh.

### ISSUE THREAD

**Issue by altava-sgp** [DSaurus/threestudio-dreamcraft3D#7]
This is error log.
```shell
$ python launch.py --config custom/threestudio-dreamcraft3D/configs/dreamcraft3d-texture.yaml --export system.prompt_processor.prompt="a 3d model of a lion standing on a gray background" data.image_path="load/images/stable-diffusion-xl-lion-3d_rgba.png" resume="outputs/dreamcraft3d-texture/a_3d_model_of_a_lion_standing_on_a_gray_background@20231222-025037/ckpts/last.ckpt" system.exporter.context_type=cuda

Import times for custom modules:
   0.1 seconds: custom/threestudio-mvdream
   0.2 seconds: custom/threestudio-dreamcraft3D

Global seed set to 0
Traceback (most recent call last):
  File "/home/dreamer/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 43, in __init__
    self.cfg = parse_structured(self.Config, cfg)
  File "/home/dreamer/threestudio/threestudio/utils/config.py", line 127, in parse_structured
    scfg = OmegaConf.structured(fields(**cfg))
  File "/home/dreamer/.local/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/dreamer/.local/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/dreamer/.local/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/dreamer/.local/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/dreamer/.local/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/dreamer/.local/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "/home/dreamer/.local/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: system.geometry_convert_from
    full_key: system.geometry_convert_from
    object_type=dict
```

The new command you added is here.
```shell
python launch.py --config custom/threestudio-dreamcraft3D/configs/dreamcraft3d-texture.yaml --export system.prompt_processor.prompt="a 3d model of a lion standing on a gray background" data.image_path="load/images/stable-diffusion-xl-lion-3d_rgba.png" resume="outputs/dreamcraft3d-texture/a_3d_model_of_a_lion_standing_on_a_gray_background@20231222-025037/ckpts/last.ckpt" system.exporter.context_type=cuda
```

What can I do ?

**Comment by altava-sgp** [comment]
This works well.
```shell
python launch.py --config outputs/dreamcraft3d-texture/a_3d_model_of_a_lion_standing_on_a_gray_background@20231222-025037/configs/parsed.yaml --export --gpu 0 resume=outputs/dreamcraft3d-texture/a_3d_model_of_a_lion_standing_on_a_gray_background@20231222-025037/ckpts/last.ckpt system.exporter_type=mesh-exporter system.exporter.context_type=cuda
```

**Comment by altava-sgp** [comment]
ok. I missed to pull. 👎
