### ISSUE TITLE
adjust output mesh resolution

### ISSUE THREAD

**Issue by vlxxc** [DSaurus/threestudio-dreamcraft3D#8]
Hi

How to adjust the output mesh resolution. 
Threestudio default has> system.geometry.isosurface_resolution=256

**Comment by DSaurus** [comment]
Hi @vlxxc ,

You could adjust the mesh resolution by setting the isosurface_resolution from 128 to 256.

**Comment by vlxxc** [comment]
Hi
When i adjust the isosurface resolution i get following error: 
FileNotFoundError: [Errno 2] No such file or directory: 'load/tets/256_tets.npz'

if i do not set isosurface resolution mesh exports at default resolution.

**Comment by user-vm** [comment]
You can generate 256_tets.npz using load/tets/generate_tets.py. After building [quartet](https://github.com/crawforddoran/quartet), you need to change the value of root and change the res list in the for to contain the resolutions you want (so "for res in [256]:" in this case).
But after doing this,
`python launch.py --config custom/threestudio-dreamcraft3D/configs/dreamcraft3d-texture-fast.yaml --export system.prompt_processor.prompt="$prompt" data.image_path="$image_path" resume="$ckpt" system.exporter.context_type=cuda system.geometry.isosurface_resolution=256`
fails with
```
Traceback (most recent call last):
  File "/home/v/2023/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/home/v/2023/threestudio/launch.py", line 259, in main
    trainer.predict(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in predict
    return call._call_and_handle_interrupt(
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 903, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 955, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 276, in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/v/2023/threestudio/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageConditionDreamFusion:
	size mismatch for geometry.sdf: copying a param with shape torch.Size([277410, 1]) from checkpoint, the shape in current model is torch.Size([2158402, 1]).
	size mismatch for geometry.deformation: copying a param with shape torch.Size([277410, 3]) from checkpoint, the shape in current model is torch.Size([2158402, 3]).
```

But it works without `system.geometry.isosurface_resolution=256`.
